### ISSUE TITLE
Meta meta issue

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#206]
## Data ingestion and processing

```
obs <- ...
data <- as_latent_individual(obs)
```

* [x] https://github.com/epinowcast/epidist/issues/313

## Model

```
fit <- epidist(data, family = brms::lognormal(), formula = list(mu ~ 1, sigma ~ 1), fn = brms::brm)
```

* [x] `family` is either a `brmsfamily` or `family` object
* [x] `formula` is a `brmsformula` for all (or some subset of) distributional parameters
* [x] No way to pass in priors currently: remains to do
  * #234

## Postprocessing

* [x] #238
* Should rely on existing functionality as much as possible e.g. `tidybayes`
* Use #48 for documentation driven development

## Plotting

* [ ] https://github.com/epinowcast/epidist/issues/303
* Based on output of postprocessing i.e. result from `tidybayes`
* Use #48 for documentation driven development

## Infrastructure

* [x] #236

#### Vignettes

* [x] #48

#### Bugs

* [x] #180
* [x] #226

#### Documentation

* [x] #132
* [x] #192
* [x] #162
* [x] #216
* [ ] #157
* [x] #166

#### Vignettes

* [ ] #64

#### Bugs

* [x] #235
