### ISSUE TITLE
Prior functionality redesign meta

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#234]
We have many issues about priors. In order of introduction:

* [x] https://github.com/epinowcast/epidist/issues/108
* [ ] https://github.com/epinowcast/epidist/issues/123
* [x] https://github.com/epinowcast/epidist/issues/172
* [x] https://github.com/epinowcast/epidist/issues/196
* [x] https://github.com/epinowcast/epidist/issues/197
* [x] https://github.com/epinowcast/epidist/issues/212

I have also worked on code relating to priors in PR https://github.com/epinowcast/epidist/pull/232. The reason for this is because bugs exist when we try to set priors on parameters which are not in the model. This is due to the current prior implementation.

## Requirements

For `epidist` 0.1.0 my vision of what we should support is as follows:

* Allow users to pass new priors into `epidist` and those priors overwrite anything. If they aren't in the model, `brms` won't run and it will warn the user
* For some parameters, we should set custom `epidist` priors using [prior predictive checks](https://epidist.epinowcast.org/articles/faq.html#how-did-you-choose-the-default-priors-for-epidist). The reason for this is that we have better knowledge of reasonable priors than `brms` defaults
* This functionality should be set-up so as to be extensible to new models, and implemented in a "reasonable" way across families

## Plan

My view of a plan to achieve these requirements:

* The function `epidist_prior` can be altered to return all priors in the model, rather than only the changed priors. It will do this by making use of `brms::default_prior`
* We add a helper function `replace_prior` which is as follows:

```
replace_prior(old_prior, new_prior) {
  # checks if any of new_prior are in old_prior
  # if that is the case, then replaces those entries
  # perhaps leaves a message saying what has been updated 
}
```

* This helper function can be used to 1. replace `brms` default priors with our favoured priors, 2. replace any priors passed by the user as priority

```
priors <- replace_prior(brms_defaults, what_we_think)
priors <- replace_prior(priors, what_user_provides)
```

* This set-up fixes issues related to passing priors on parameters which don't exist
* Allows us to suggest that users call `epidist_prior` to see all the priors used in the model
* For the time being, we can use `if` statements within model specific dispatch `epidist_prior` to set family/link function specific priors. However, we should write things as follows, such that things are modular enough that when we create `epidist_prior.newmodel` we are starting from a good position to figure out what can be put into shared functions
  * Hard to be sure, but expect that much of prior functionality is shared across models

```
lognormal_priors <- brms::prior(...) + brms::prior(...)
priors <- replace_prior(brms_defaults, lognormal_priors)
```

* It will be easy for me to run more prior predictive checks once this functionality is in, and update more family suggested priors
* I think that for the time being we can count #123 (passing priors on non-`brms` quantities) as a nice-to-have but not essential feature

**Comment by seabbs** [comment]
I think the tooling for updating the priors should be independent i.e in a different function from any model or family specific priors. This means we don't need to worry about s3 classes. I also think we need to distinguish between model and family based piors. One potential design is as follows. 

```r
epidist_prior <- function(data, family, formula, priors) {

	 default <- brms::default_priors(data, family, formula)
     model <- epidist_model_priors(data, formula)
     family <  epidist_family_priors(family, formula)
    priors <- reduce(list(default, model, family, priors), replace_priors) # this is very peuedo codee for a function that iteratively applies
   return(priors)
}

**Comment by athowes** [comment]
Yes I can see how this suggestion would work. And it's clever to be dispatching on `data` for the model and for `family` for the family. Basically like multiple dispatch in some way.

One challenge is that the `family` object does not currently have a class. So to do this we would need to add something like

```
epidist_family.epidist_latent_individual <- function() {
  ...
  class(family) <- "something"
}
```

I don't mind adding this (though I do feel a bit unsure about adding many class systems).

In terms of right now, I think both the original proposal and this newer proposal would be fine. I can see why you'd think the newer proposal would be more extensible.

I do think for the newer proposal, we would also want to be having different priors for the link functions as I've send. Hence one could argue it's a bit ugly in some ways to be dispatching on classes for the family and then internal to that using `if` statements (as compared with using `if` statements for everything).

About the `epidist_model_priors.default` function: this is going to need to alter the Stan code potentially. My older proposal also has the issue of not having dealt with this though.

**Comment by seabbs** [comment]
>  Basically like multiple dispatch in some way.

Yes exactly. 

> One challenge is that the family object 

The brms input does though doesn't it? If we can we want the family to be based on this and not a custom family (i.e latent_lognormal). 

> one could argue it's a bit ugly in some ways to be dispatching on classes for the family and then internal to that using if statements for the link specific priors (as compared with using if statements for everything)

I think this is fine as its family specific and the family we are passing knows what link functions they have. I think also dispatching on links could be done but might be a bit mad complexity wise.

> About the epidist_model_priors.default function: this is going to need to alter the Stan code potentially. My older proposal also has the issue of not having dealt with this though.

Yes potentially (or contain stan code). I think we should just build the structure for now and circle back to that at a later date (as IMO I don't think we need it for `0.1.0`).

**Comment by athowes** [comment]
> The brms input does though doesn't it? 

If you're talking about something like `brms::lognormal` then no it doesn't have `"lognormal"` as a class:

```
> class(brms::lognormal())
[1] "brmsfamily" "family"
```

> the family we are passing knows what link functions they have

Right but the family also knows what family it is so it feels to me like the same logic applies. But ultimately I'm fine with this. I don't think we should dispatch on links. (But in terms of complexity, this feeling complex to dispatch on family is the same vibe as it feeling complex to dispatch on link.)

>  think we should just build the structure for now

You could argue that this structure we were are expecting `model_priors` to fit into the same format as all the other priors is less compatible with having to include Stan code than a less structured approach. We can carve out an exception and not `reduce` it, or whatever, but to note.

**Comment by seabbs** [comment]
>  I don't think we should dispatch on links.

Strongly agree.

> h having to include Stan code than a less structured approach

I can see where you are coming from. I think what I would propose for that extension is to change the replace_priors arg to know about potential stan code but as I said above I think we are a way away from needing that functionality.

**Comment by athowes** [comment]
I'm fine with having family classes. I think there is a complexity here about whether the class is on:

1. The output of `epidist_family` i.e. a custom family
2. The input `brms` or `stats` family

I don't fully understand the ramifications / possibility of putting the family on either of these. This relates to an overall confusion I have about the `epidist_x` and `x` (see https://github.com/epinowcast/epidist/issues/198).

From my point of view I think I'm happy to go ahead with implementation of this proposal: https://github.com/epinowcast/epidist/issues/234#issuecomment-2275936515

**Comment by seabbs** [comment]
I think we want it to not be the custom family as the custom family is really model specific and so doesn't give us the ability to make models and families independent.

**Comment by kgostic** [comment]
> Allow users to pass new priors into epidist and those priors overwrite anything. If they aren't in the model, brms won't run and it will warn the user

If this is still the plan, and if we're proposing an error for parameters that don't exist in the model, it would be great if it's possible to have the error message include a list of the parmeters needed, e.g. "Prior inputs contain parameters that do not exist in this model. You input {user_params}. Your model contains these parameters: {model params from brms}."

**Comment by athowes** [comment]
> If this is still the plan, and if we're proposing an error for parameters that don't exist in the model, it would be great if it's possible to have the error message include a list of the parmeters needed, e.g. "Prior inputs contain parameters that do not exist in this model. You input {user_params}. Your model contains these parameters: {model params from brms}."

I think this can be implemented as an option within the function `replace_priors`. It could either be a warning or an error. If it's a warning then `brms` will error. If it's an error then it'll stop the process sooner. I imagine we'd use the error version:

```
replace_prior(old_prior, new_prior) {
  # checks if any of new_prior are in old_prior
  # if that is the case, then replaces those entries
  # perhaps leaves a message saying what has been updated
  # option to either error or warn users that there are priors in new_prior that aren't in old_prior
}
```

**Comment by athowes** [comment]
IMO #123 is not required for next release. So I'm closing this issue as completed! 🥳
