### ISSUE TITLE
Infrastructure meta

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#236]
We have a range of infrastructure issues that I'm compiling here (work in progress):

## High priority

* [ ] #105 the package size is big
* [ ] #177

## Medium and low priority

* [x] #178 we've had some issues with the merge queue, so I think it's off for now
* [ ] #120 this is about a particular vignette failing `R CMD CHECK`. I don't know if we still have this issue? Or is it that we don't have it because we disabled Mac CLI?
* [x] #165 this is the issue where @seabbs talks about disabling Mac CLI to hotfix a fail. I think it could be that #120 is a duplicate of this, and it was failing due to not having `cmdstanr` installed?
* [x] #229 sometimes our tests fail for weird reasons: I don't understand what is going on here
* [x] #143
  * [x] https://github.com/epinowcast/epidist/issues/147
  * [x] https://github.com/epinowcast/epidist/issues/148
  * [x] #357 
* [ ] #96 for CRAN we need to figure out how to get vignettes to build. This is fine to leave because we're not aiming to be on CRAN immediately I don't think
