### ISSUE TITLE
Ebola vignette clean-up

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#290]
The Ebola vignette PR (#52) got really big. There are a few comments left to go over but I recommend we merge a rougher version of the vignette, then I'll pick these up in a new issue. One reason for that is that I'm finding it a bit unweildy with such a large comment history.

* [x] https://github.com/epinowcast/epidist/pull/52#discussion_r1742079253 Should we use `bf(mu ~ 1, sigma ~ 1)` or just leave as default. I prefer writing it out, Sam prefers leaving it as default.
* [x] https://github.com/epinowcast/epidist/pull/52#discussion_r1742068658 Should we have facet specific x-axis for the plot showing the data. I prefer no, Katie prefers yes. (Moved to https://github.com/epinowcast/epidist/issues/285)
* [x] https://github.com/epinowcast/epidist/pull/52#discussion_r1742271807 Could we simplify `ptime` and `ptime_daily`. See #291 also. (Moved to https://github.com/epinowcast/epidist/issues/285)
* [x] https://github.com/epinowcast/epidist/pull/52#discussion_r1743966633 Better explainations of what is happening in the PMF and PDF prediction generation. From my perspective, I understand them as being predictions of something. Why this is exactly what you want for policy purposes I understand less. For example, why do you want to predict what you would observe with censoring for the PMF, rather than what you would observe without censoring and then discretise that? I somewhat get it but not all the way (and if I'm confused then readers will be also I think). This relates to the "going around in circles"-esque discussion on the initial vignette and follow-up issue e.g. https://github.com/epinowcast/epidist/issues/67 (Moved to https://github.com/epinowcast/epidist/issues/285)
* [x] https://github.com/epinowcast/epidist/pull/52#discussion_r1743990310 Possible reordering of sections. I'm open to this. Also would fit into "possible regrouping of plots". Right now I've grouped all models for a particular plot type
* [x] https://github.com/epinowcast/epidist/pull/52#discussion_r1750572702 Need to make sure it's consistent in use of `::` in text the first time a function is introduced and then not using `::` in code. Also using `()` to get automatic `pkgdown` links

## Other things I notice

* [x] Title has ` failing to render properly
* [x] Maths is failing to render properly e.g. \(x \sim \mathcal{N}(\mu, \sigma)\). (Moved to #333)
* [x] Calling `head(obs_prep)` twice
* [x] I don't like that I have to call `sex = case_when` over and over -- way to fix this?
* [x] Figure 2.3 panel C is too small / needs sorting
* [x] Figure 2.4 panel C also too small / needs sorting

**Comment by athowes** [comment]
@seabbs that's fair regarding this being 6 issues vs 1 issue. I don't have enough personal experience to have preference yet but I can see the appeal of 6 issues. It was easier for me initially to do 1 issue and it felt like "I just want to get this gone" hence where we are.

**Comment by seabbs** [comment]
I think I would track this with a meta-issue but assign each as individual issues to give the option of splitting into their own PRs

**Comment by athowes** [comment]
> Should we use bf(mu ~ 1, sigma ~ 1) or just leave as default. I prefer writing it out, Sam prefers leaving it as default.

@seabbs can we leave this as it is for the time being? We are likely making changes to the formula interface anyway soon.
