### ISSUE TITLE
Plotting meta

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#303]
## Background

* In PR #292 we removed all of the old plotting functionality from this package.
* I think that this package should have some plotting functionality, but it should be focused on figures that are sufficiently commonly required and with enough "gotchas" that users might find it hard to produce them themselves
* With this in mind, I think that we likely _shouldn't_ be providing plotting functionality aimed at users running simulation studies like that of https://github.com/parksw3/epidist-paper

## Existing plots in vignettes

* [Getting started with epidist](https://epidist.epinowcast.org/articles/epidist.html)
  * Plot of the primary and secondary event times in the data
  * Plot of discrete delay probability mass functions and continuous density functions 
* [Using epidist to estimate stratified delays between symptom onset and positive test for the 2014-2016 Ebola outbreak in Sierra Leone](https://epidist.epinowcast.org/articles/ebola.html)
  * Plot of the primary and secondary event times in the data (facet by district)
  * Plot of various posterior distributions with `stat_pointinterval()` family (facet or y-axis by various things)
  * Plot of PMFs and PDFs with `geom_bar` or `geom_density`
* [Approximate Bayesian inference in epidist](https://epidist.epinowcast.org/articles/approx-inference.html)
  * Plot of posterior distributions (with old style, should be updated to use `tidybayes`)
  * Plot of PDFs with `geom_density` (comparison)
  
## Other ideas not in vignettes at the moment

* Posterior plot (point and interval) of the estimated delay parameters to include both `brms` parameters and natural scale parameters
* Estimated delay distribution figures to include
  1. Uncertainty
  2. Observed frequencies (i.e. the data)
  
## Synthesis of what I think we should support

1. Some way to visualise the observed data. Similar to the plot of primary and secondary event times in the vignettes. Maybe this interacts somehow with preprocessing or model classes.
2. Some way to plot generated discrete and continuous representations of delay distributions, ideally on the same figure. Perhaps we need some structure for how the outputs should look.
  * Perhaps the part about being able to combine discrete and continuous, and various facets or otherwise, might be challenging
  * I think we should be able to include the data in this plot
  * And I think being able to visualise uncertainty here would be good
3. (Maybe) some kind of helper for plotting posterior distributions of delay parameters (and on the natural scale)

## Next steps

* [ ] Get input from others on these ~ two figures being what we should support
* [ ] Draft versions of the two figures
  * Standard documentation, tests, ...
* [ ] Replace existing figures in the vignette with this code

**Comment by seabbs** [comment]
I am currently thinking that we probably don't want to support plots of any kind

**Comment by athowes** [comment]
Happy to close and come back to it if we later decide to include plots.

I think there could be an argument about supporting plots of non-output data e.g. where we have classes like `epidist_linelist`. This way they don't have to be (as) generalisable.

**Comment by seabbs** [comment]
Yes good point. I think I see that as its own issue so going to close for now. it might good a good idea to open specific plot issues and we can take it from there?
